language: ruby

services:
  - mysql
  - postgresql

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

matrix:
    allow_failures:
      - rvm: jruby

env:
  global: REDMINE_PATH=$HOME/redmine
  matrix:
    - REDMINE_VER=master DB=mysql
    - REDMINE_VER=master DB=postgresql

before_install:
  - export PLUGIN_NAME=redmine_blocked_reason
  - git clone https://github.com/redmine/redmine.git --branch $REDMINE_VER --depth 1 $REDMINE_PATH
  - git clone https://github.com/ZitecCOM/redmine_testing_gems.git --branch 1.3.3 --depth 1 $REDMINE_PATH/plugins/redmine_testing_gems
  - cp -R $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH
  - bundle install --without development rmagick

before_script:
  - bundle exec rake db:create db:migrate redmine:plugins:migrate RAILS_ENV=test

script:
  - bundle exec rake redmine:plugins:spec RAILS_ENV=test NAME=$PLUGIN_NAME
